### ISSUE TITLE
Todo: Various

### ISSUE THREAD

**Issue by Cryomundus** [Cryomundus/Hdest-Diablonium#1]
- [ ] Add FreeDoom compat
- [ ] Revise the big devilers, and redo palette to be less ugly
- [ ] kitbash new sounds for all worms
- [ ] revise haunted pillar
- [ ] Add spawn toggles BEFORE ADDING ANYMORE CONTENT
- [ ] Add Grimler
- [ ] Add Vitreol 
- [ ] Add OneWhoSees 
- [ ] Add The Tyrant's Eyes
- [ ] Add The Pests: Sessners, Wraithlings, A literal scorpion, Beezelkeek, MeatPod, Podlings
- [ ] Add GasselGhast
- [ ] Add Dabibiyuk
